# View pre-commit hooks at https://github.com/pre-commit/pre-commit-hooks#hooks-available
# !!!RUN pre-commit autoupdate!!! To get the latest versions. This gist has been collecting dust bunnies and cob webs.
# The commented repos/hooks will NOT autoupdate! If you're going to use them, uncomment and run pre-commit autoupdate.

default_language_version:
    python: python3.8

default_stages: [commit, push]

fail_fast: true

minimum_pre_commit_version: '1.15.0'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Preserve Markdown hard linebreaks
          #
    # Docformatter https://pypi.org/project/docformatter/
-   repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args:
          - --in-place
          - -r
          - --blank
          - --recursive
          - --wrap-summaries=72
          - --wrap-descriptions=72
          - --pre-summary-newline
          - --make-summary-multi-line

    # Add trailing commas https://github.com/asottile/add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma

    # iSort https://pycqa.github.io/isort/
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        args:
          - --trailing-comma
          - --use-parentheses
          - --balanced
          - --py=38
          - --profile=black
          - -l=79

    # Black https://black.readthedocs.io/en/stable/
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
          - --target-version=py38
          - --line-length=79

    # Flask8 https://flake8.pycqa.org/en/latest/index.html#
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        exclude: description.py
        additional_dependencies: [
          pep8-naming,
]
        args:
          - --doctests

    # Unimport https://unimport.hakancelik.dev/#/
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.6.8
    hooks:
    -   id: unimport
        args:
          - --remove
          - --requirements
          - --include-star-import
          - --gitignore

    # Pyupgrade https://github.com/asottile/pyupgrade
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade

    # Saftey https://pyup.io/safety/
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
      #
    # Bandit https://github.com/PyCQA/bandit
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.6.3
#     hooks:
#     -   id: bandit
# Below is opinionated linters and formatters. Uncomment at your own risk!
#       # Interrogate https://interrogate.readthedocs.io/en/latest/
-   repo: https://github.com/econchick/interrogate
    rev: 7a0823fb29ddcd955eaf3aa91e7e93c8ca6bfbfd
    hooks:
    -   id: interrogate
        args:
          - --fail-under=95
          - --verbose
          - --ignore-init-method
          - --ignore-init-module
#   # Dotenv Linter https://dotenv-linter.readthedocs.io/en/latest/index.html
# - repo: https://github.com/wemake-services/dotenv-linter
#   rev: 0.2.0  # Use the ref you want to point at
#   hooks:
# -   id: dotenv-linter
#
#     # MyPy https://github.com/pre-commit/mirrors-mypy
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: f687d36b12cd72d417bba07599ff27e734161768
#     hooks:
#     -   id: mypy
#         args: [--no-strict-optional, --ignore-missing-imports]
#
#     # Re-Order Imports https://github.com/asottile/reorder_python_imports
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: 925baf70b8fe1467ac1712ddd6793d52978a4a72
#     hooks:
#     -   id: reorder-python-imports
#
#
#     # Swagger-CLI validator https://apitools.dev/swagger-cli/
# -   repo: https://github.com/APIDevTools/swagger-cli
#     rev: 9fec0bce6954a1bf7d396a6356f9c93780a92da7
#     hooks:
#     -   id: swagger-validation
#         args: ["validate", "<path to root swagger>"]
#
#   # Git Tickect https://giticket.readthedocs.io/en/latest/
# -  repo:  https://github.com/milin/giticket  # View docs to see how to set up custom ticket.
#    rev: <grab the latest commit hash>
#    hooks:
#    -   id:  giticket
#        args: ['--regex=PROJ-[0-9]', '--format={ticket} {commit_msg}']  # Optional
